# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x05greet\"\x0f\n\rmensagemVazia\"#\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07valores\x18\x02 \x01(\t\"$\n\x05Users\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07valores\x18\x02 \x01(\t\",\n\rrequestUpdate\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07valores\x18\x02 \x01(\t\"\x19\n\x0brequestUser\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xca\x01\n\x07Greeter\x12)\n\ncreateUser\x12\x0b.greet.User\x1a\x0c.greet.Users\"\x00\x12-\n\x07getUser\x12\x12.greet.requestUser\x1a\x0c.greet.Users\"\x00\x12\x31\n\ndeleteUser\x12\x0b.greet.User\x1a\x14.greet.mensagemVazia\"\x00\x12\x32\n\nupdateUser\x12\x14.greet.requestUpdate\x1a\x0c.greet.Users\"\x00\x62\x06proto3')



_MENSAGEMVAZIA = DESCRIPTOR.message_types_by_name['mensagemVazia']
_USER = DESCRIPTOR.message_types_by_name['User']
_USERS = DESCRIPTOR.message_types_by_name['Users']
_REQUESTUPDATE = DESCRIPTOR.message_types_by_name['requestUpdate']
_REQUESTUSER = DESCRIPTOR.message_types_by_name['requestUser']
mensagemVazia = _reflection.GeneratedProtocolMessageType('mensagemVazia', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEMVAZIA,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:greet.mensagemVazia)
  })
_sym_db.RegisterMessage(mensagemVazia)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:greet.User)
  })
_sym_db.RegisterMessage(User)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), {
  'DESCRIPTOR' : _USERS,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:greet.Users)
  })
_sym_db.RegisterMessage(Users)

requestUpdate = _reflection.GeneratedProtocolMessageType('requestUpdate', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUPDATE,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:greet.requestUpdate)
  })
_sym_db.RegisterMessage(requestUpdate)

requestUser = _reflection.GeneratedProtocolMessageType('requestUser', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUSER,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:greet.requestUser)
  })
_sym_db.RegisterMessage(requestUser)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MENSAGEMVAZIA._serialized_start=21
  _MENSAGEMVAZIA._serialized_end=36
  _USER._serialized_start=38
  _USER._serialized_end=73
  _USERS._serialized_start=75
  _USERS._serialized_end=111
  _REQUESTUPDATE._serialized_start=113
  _REQUESTUPDATE._serialized_end=157
  _REQUESTUSER._serialized_start=159
  _REQUESTUSER._serialized_end=184
  _GREETER._serialized_start=187
  _GREETER._serialized_end=389
# @@protoc_insertion_point(module_scope)
